blank_issues_enabled: true
contact_links:
  - name: Contact Me On Instagram
    url: https://github.community/
    about: Please ask and questions here.
  - name: Contact Me On Linkedln
    url: https://www.linkedin.com/in/prathameshborse/
    about: Please connect with me here.